# app/modules/points/constants.py
"""
积分账本常量

本文件集中保存积分账户状态、冻结状态、流水方向和积分规则状态，避免各能力模块散落
硬编码字符串。这些常量只表达账本事实，不代表权限点，也不代表前端展示文案。
"""

POINT_ACCOUNT_ACTIVE = "active"

POINT_HOLD_ACTIVE = "active"
POINT_HOLD_RELEASED = "released"
POINT_HOLD_DEDUCTED = "deducted"

POINT_DIRECTION_INCOME = "income"
POINT_DIRECTION_EXPENSE = "expense"
POINT_DIRECTION_FREEZE = "freeze"
POINT_DIRECTION_UNFREEZE = "unfreeze"
POINT_DIRECTION_HOLD_DEDUCT = "hold_deduct"
POINT_DIRECTION_REVERSAL = "reversal"

POINT_RULE_STATUS_ACTIVE = "active"
POINT_RULE_STATUS_REVOKED = "revoked"

POINT_RULE_TYPE_FIXED = "fixed"
POINT_RULE_TYPE_TEMPORARY_TASK_TEMPLATE = "temporary_task_template"

TEMPORARY_POINT_RULE_APPROVAL_PENDING = "pending"
TEMPORARY_POINT_RULE_APPROVAL_APPROVED = "approved"
TEMPORARY_POINT_RULE_APPROVAL_REJECTED = "rejected"

TEMPORARY_POINT_RULE_REVOKE_NONE = "none"
TEMPORARY_POINT_RULE_REVOKE_ACTIVE = "active"
TEMPORARY_POINT_RULE_REVOKE_REVOKED = "revoked"

TEMPORARY_POINT_RULE_EVENT_SUBMITTED = "submitted"
TEMPORARY_POINT_RULE_EVENT_APPROVED = "approved"
TEMPORARY_POINT_RULE_EVENT_REJECTED = "rejected"
TEMPORARY_POINT_RULE_EVENT_REVOKED = "revoked"
